JuanApp/Controllers/BasketController.cs
using JuanApp.Models;
using JuanApp.Models.Data;
using JuanApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;

namespace JuanApp.Controllers
{
    public class BasketController : Controller
    {
        private readonly JuanAppDb _context;
        private readonly ICompositeViewEngine _viewEngine;

        public BasketController(JuanAppDb context, ICompositeViewEngine viewEngine)
        {
            _context = context;
            _viewEngine = viewEngine;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddToBasket(int id)
        {
            if (id == 0) 
                return Json(new { success = false, message = "Invalid product" });

            Products product = _context.products
                .Include(c => c.Color)
                .FirstOrDefault(p => p.Id == id);

            if (product == null) 
                return Json(new { success = false, message = "Product not found" });

            var basket = HttpContext.Request.Cookies["basket"];
            List<BasketVm> basketItems = string.IsNullOrWhiteSpace(basket) 
                ? new List<BasketVm>() 
                : System.Text.Json.JsonSerializer.Deserialize<List<BasketVm>>(basket);

            BasketVm basketItem = basketItems.FirstOrDefault(bi => bi.PeoductId == id);

            if (basketItem == null)
            {
                basketItem = new BasketVm
                {
                    PeoductId = id,
                    Count = 1,
                    Name = product.Name,
                    Price = product.Price,
                    Image = product.Imageurl
                };
                basketItems.Add(basketItem);
            }
            else
            {
                basketItem.Count++;
            }

            // Save cookie
            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(7),
                IsEssential = true,
                Secure = true,
                HttpOnly = true,
                SameSite = SameSiteMode.Lax
            };

            var serializedBasket = System.Text.Json.JsonSerializer.Serialize(basketItems);
            HttpContext.Response.Cookies.Append("basket", serializedBasket, cookieOptions);

            // Render partial view
            var basketViewModel = new
            {
                ItemCount = basketItems.Sum(x => x.Count),
                Items = basketItems,
                TotalPrice = basketItems.Sum(x => x.Price * x.Count)
            };

            var basketHtml = RenderViewToStringAsync("_BasketPartial", basketViewModel).Result;

            return Json(new
            {
                success = true,
                basketCount = basketViewModel.ItemCount,
                basketHtml = basketHtml,
                message = "Product added to cart successfully"
            });
        }

        private async Task<string> RenderViewToStringAsync(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.ActionDescriptor.ActionName;

            ViewData.Model = model;

            using (var writer = new StringWriter())
            {
                IViewEngine viewEngine = HttpContext.RequestServices.GetService(typeof(ICompositeViewEngine)) as ICompositeViewEngine;
                ViewEngineResult viewResult = viewEngine.FindView(ControllerContext, viewName, false);

                if (viewResult.View == null)
                    throw new ArgumentNullException($"{viewName} does not match any available view");

                var viewContext = new ViewContext(
                    ControllerContext,
                    viewResult.View,
                    ViewData,
                    TempData,
                    writer,
                    new HtmlHelperOptions()
                );

                await viewResult.View.RenderAsync(viewContext);

                return writer.GetStringBuilder().ToString();
            }
        }
    }
}

JuanApp/Views/Shared/_BasketPartial.cshtml
@model dynamic

<div class="minicart-content-box">
    <div class="minicart-item-wrapper">
        <ul>
            @foreach (var item in Model.Items)
            {
                <li class="minicart-item">
                    <div class="minicart-thumb">
                        <a href="/Product/Details/@item.PeoductId">
                            <img src="/assets/img/product/@item.Image" alt="@item.Name">
                        </a>
                    </div>
                    <div class="minicart-content">
                        <h3 class="product-name">
                            <a href="/Product/Details/@item.PeoductId">@item.Name</a>
                        </h3>
                        <p>
                            <span class="cart-quantity">@item.Count <strong>&times;</strong></span>
                            <span class="cart-price">$@item.Price</span>
                        </p>
                    </div>
                    <button class="minicart-remove" data-id="@item.PeoductId"><i class="ion-android-close"></i></button>
                </li>
            }
        </ul>
    </div>

    <div class="minicart-pricing-box">
        <ul>
            <li class="total">
                <span>Total</span>
                <span><strong>$@Model.TotalPrice</strong></span>
            </li>
        </ul>
    </div>

    <div class="minicart-button">
        <a href="@Url.Action("Index", "Basket")"><i class="fa fa-shopping-cart"></i> view cart</a>
        <a href="@Url.Action("Checkout", "Basket")"><i class="fa fa-share"></i> checkout</a>
    </div>
</div>

JuanApp/Views/Shared/_ProductCardPartial.cshtml
@model Products

<div class="product-item mb-50">
    <div class="product-thumb">
        <a href="@Url.Action("Details", "Product", new { id = Model.Id })">
            <img src="~/assets/img/product/@Model.Imageurl" alt="@Model.Name" />
        </a>
    </div>
    <div class="product-content">
        <h5 class="product-name">
            <a href="@Url.Action("Details", "Product", new { id = Model.Id })">@Model.Name</a>
        </h5>
        <div class="price-box">
            <span class="price-regular">$@Model.Price</span>
            <span class="price-old"><del>$@Model.DiscountPrice</del></span>
        </div>
        <div class="product-action-link">
            <a href="#" class="add-to-wishlist" data-id="@Model.Id" data-toggle="tooltip" title="Wishlist">
                <i class="@Model.WishListIcon"></i>
            </a>
            <a href="#" class="add-to-cart" data-id="@Model.Id" data-toggle="tooltip" title="Add To Cart">
                <i class="@Model.AddtocartIcon"></i>
            </a>
            <a href="#" class="quick-view" data-id="@Model.Id" data-toggle="modal" data-target="#quick_view">
                <span data-toggle="tooltip" title="Quick View">
                    <i class="@Model.QuickViewIcon"></i>
                </span>
            </a>
        </div>
    </div>
</div>